language: node_js
node_js:
    - "8"

env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - GIT_BRANCH: master

sudo: required
dist: trusty

before_script:
  - pip install mkdocs

addons:
  code_climate:
    repo_token: ${CODE_CLIMATE_TOKEN}
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

 # Run npm test always
script:
    - npm run lint
    - npm test
    - node build.js

after_success:
  - nyc report --reporter=text-lcov | coveralls
