language: node_js
node_js:
    - "8"
group: deprecated-2017Q3
env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - GIT_BRANCH: master

sudo: required
dist: trusty

addons:
  code_climate:
    repo_token: ${CODE_CLIMATE_TOKEN}
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - oracle-java8-set-default
    - python3
    - python3-pip

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb && sudo service elasticsearch start
  - pip3 install mkdocs
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
    - npm run lint || travis_terminate 1
    - npm test || travis_terminate 1
    - npm run docs || travis_terminate 1
    - npm run build || travis_terminate 1

after_success:
  - cat ./coverage/lcov.info | coveralls
