language: python
python:
  - "3.5"
node_js:
    - "10"

dist: trusty
sudo: required

env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - GIT_BRANCH: master

services:
  - elasticsearch

addons:
  chrome: stable

before_install:
  - pip3 install mkdocs
  - pip3 install mkdocs-material

script:
    - npm install
    - PATH=${PATH}:\.\/node_modules\/\.bin/
    - npm run lint
    - npm test
    - codecov
    - npm run docs
    - mkdocs build
    - npm run build
    - npm run build -- --dist
    - npm install --prefix integration
    - npm run test:integration

after_success:
  - npm run deploy
