language: node_js
node_js:
    - "8"
group: deprecated-2017Q3
env:
    global:
        - GIT_NAME: Travis CI
        - GIT_EMAIL: builds@travis-ci.org
        - GIT_BRANCH: master

sudo: required
dist: trusty

addons:
  code_climate:
    repo_token: ${CODE_CLIMATE_TOKEN}
  apt:
    chrome: stable
    packages:
    - oracle-java8-set-default
    - python3
    - python3-pip

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb && sudo service elasticsearch start
  - pip3 install mkdocs
script:
    - npm run lint
    - npm test
    - codecov
    - npm run docs
    - npm run build
    - npm install --prefix integration
    - npm run test:integration

after_success:
  - npm run deploy
