copyright: Copyright &copy; 2017

site_name: LokiDB
repo_url: https://github.com/LokiJS-Forge/LokiDB
repo_name: GitHub

extra_css:
  - css/codemirror/codemirror.css
  - css/codemirror/foldgutter.css
  - css/javascript_editor.css

extra_javascript:
  - js/gitter.js
  - js/javascript_editor.js
  - js/codemirror/lib/codemirror.js
  - js/codemirror/addon/fold/brace-fold.js
  - js/codemirror/addon/fold/foldcode.js
  - js/codemirror/addon/fold/foldgutter.js
  - js/codemirror/addon/edit/matchbrackets.js
  - js/codemirror/mode/javascript/javascript.js
  - js/@lokijs/lokijs.fs-storage.min.js
  - js/@lokijs/lokijs.full-text-search.min.js
  - js/@lokijs/lokijs.full-text-search-language.min.js
  - js/@lokijs/lokijs.full-text-search-language-de.min.js
  - js/@lokijs/lokijs.full-text-search-language-en.min.js
  - js/@lokijs/lokijs.indexed-storage.min.js
  - js/@lokijs/lokijs.local-storage.min.js
  - js/@lokijs/lokijs.loki.min.js
  - js/@lokijs/lokijs.memory-storage.min.js
  - js/@lokijs/lokijs.partitioning-adapter.min.js


theme: readthedocs
