copyright: Copyright &copy; 2017

site_name: LokiDB
repo_url: https://github.com/LokiJS-Forge/LokiDB
repo_name: GitHub

extra_css:
  - css/auto-complete.css
  - css/javascript_editor.css
  - css/codemirror/codemirror.css
  - css/codemirror/foldgutter.css

extra_javascript:
  - js/auto-complete.js
  - js/gitter.js
  - js/sidecar.js
  - js/javascript_editor.js
  - js/codemirror/lib/codemirror.js
  - js/codemirror/addon/fold/brace-fold.js
  - js/codemirror/addon/fold/foldcode.js
  - js/codemirror/addon/fold/foldgutter.js
  - js/codemirror/addon/edit/matchbrackets.js
  - js/codemirror/mode/javascript/javascript.js
#  - js/@lokidb/lokidb.fs-storage.min.js
#  - js/@lokidb/lokidb.full-text-search.min.js
#  - js/@lokidb/lokidb.full-text-search-language.min.js
#  - js/@lokidb/lokidb.full-text-search-language-de.min.js
#  - js/@lokidb/lokidb.full-text-search-language-en.min.js
#  - js/@lokidb/lokidb.indexed-storage.min.js
#  - js/@lokidb/lokidb.local-storage.min.js
#  - js/@lokidb/lokidb.loki.min.js
#  - js/@lokidb/lokidb.memory-storage.min.js
#  - js/@lokidb/lokidb.partitioning-adapter.min.js
  - js/monaco/app.bundle.js
  - js/monaco/main.js

theme: readthedocs
