copyright: Copyright &copy; 2017

site_name: LokiDB
repo_url: https://github.com/LokiJS-Forge/LokiDB
repo_name: GitHub

extra_css:
  - css/codemirror/codemirror.css
  - css/codemirror/foldgutter.css
  - css/javascript_editor.css

extra_javascript:
  - js/gitter.js
  - js/javascript_editor.js
  - js/codemirror/lib/codemirror.js
  - js/codemirror/addon/fold/brace-fold.js
  - js/codemirror/addon/fold/foldcode.js
  - js/codemirror/addon/fold/foldgutter.js
  - js/codemirror/addon/edit/matchbrackets.js
  - js/codemirror/mode/javascript/javascript.js


theme: readthedocs
